#!/usr/bin/env python3
"""Generate the native name tables (Kotlin + Swift) from the repo's single sources of truth.

Sources:
  data/sky.json      - graha descriptions and clock-ring legend colours
  data/glossary.json - glossary one-liners
  data/names.json  - IAST / Tamil / Devanagari names, natures, rasi <-> Tamil month (Hora)
  data/rules.json  - muhurta rules, festivals
  docs/SPEC.md §3  - Devanagari names, deities, temperaments, yoga natures, karana symbols

Run from the repo root:  python3 scripts/gen_tables.py
Outputs:
  android/core/src/main/kotlin/org/hora/panchanga/core/Tables.kt
  ios/PanchangaCore/Sources/PanchangaCore/Tables.swift
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
names = json.load(open(os.path.join(ROOT, "data/names.json"), encoding="utf-8"))
rules = json.load(open(os.path.join(ROOT, "data/rules.json"), encoding="utf-8"))
glossary = json.load(open(os.path.join(ROOT, "data/glossary.json"), encoding="utf-8"))
sky = json.load(open(os.path.join(ROOT, "data/sky.json"), encoding="utf-8"))
spec = open(os.path.join(ROOT, "docs/SPEC.md"), encoding="utf-8").read()


def spec_table(heading):
    """Rows of the first markdown table after a heading line (cells stripped of ** markup)."""
    i = spec.index(heading)
    rows = []
    for line in spec[i:].splitlines()[1:]:
        if line.startswith("|"):
            cells = [c.strip().replace("**", "") for c in line.strip().strip("|").split("|")]
            if set(cells[0]) <= set("-: "):
                continue
            rows.append(cells)
        elif rows:
            break
    return rows[1:]  # drop header


tithi_spec = spec_table("## 1. Tithi Table (30 entries)")
nak_spec = spec_table("## 2. Nakshatra Table (27 entries)")
yoga_spec = spec_table("## 3. Yoga Table (27 entries)")
kar_spec = spec_table("## 4. Karana Table (60 entries)")
vara_spec = spec_table("## 5. Vara Table (7-day Weekday)")
assert len(tithi_spec) == 30 and len(nak_spec) == 27 and len(yoga_spec) == 27
assert len(kar_spec) == 60 and len(vara_spec) == 7

ASUBHA = {1, 6, 9, 10, 13, 15, 17, 19, 27}
for r in yoga_spec:  # cross-check SPEC classification against CLAUDE.md
    assert (r[3] == "Ashubha") == (int(r[0]) in ASUBHA), r

tithi = [dict(iast=t["name"], paksha=t["paksha"], number=t["number"], family=t["family"],
              dev=tithi_spec[i][1], good=tithi_spec[i][5]) for i, t in enumerate(names["tithi"])]
nak = [dict(iast=n["iast"], dev=n["devanagari"], ta=n["tamil"], nature=n["nature"],
            deity=nak_spec[i][5], temper=nak_spec[i][6]) for i, n in enumerate(names["nakshatra"])]
yoga = [dict(iast=y["iast"], dev=yoga_spec[i][1], shubha=(i + 1) not in ASUBHA, nature=yoga_spec[i][4])
        for i, y in enumerate(names["yoga"])]
order = names["karana"]["order_by_index"]
assert len(order) == 60
# one record per distinct karana name (11), keyed by IAST, details from the SPEC row
kinfo = {}
for i, iast in enumerate(order):
    r = kar_spec[i]
    kinfo.setdefault(iast, dict(iast=iast, dev=r[1], fixed=r[3] == "Fixed", animal=r[4], nature=r[5],
                                use=r[6].replace("Avoid all", "avoid all")))
karana_names = list(kinfo.keys())
karana_order = [karana_names.index(n) for n in order]
vara = [dict(iast=v["iast"], ta=v["tamil"], lord=v["lord"], dev=vara_spec[i][1], en=vara_spec[i][3],
             nature=vara_spec[i][5]) for i, v in enumerate(names["vara"])]
rasi = [dict(iast=r["iast"], dev=r["devanagari"], month=r["tamil_month"], monthTa=r["tamil_month_script"])
        for r in names["rasi"]]
samvat = names["samvatsara"]
hora = names["hora_order_chaldean"]
kala = names["kala_eighth_parts_by_weekday"]
nature_uses = {k: dict(meaning=v["meaning"], uses=v["uses"]) for k, v in rules["nakshatra_natures"].items()}
wedding = rules["wedding"]
nak_by_iast = {n["iast"]: i for i, n in enumerate(names["nakshatra"])}
def fold(s):  # "Paṅguni" (rules.json) vs "Panguni" (names.json)
    import unicodedata
    return "".join(c for c in unicodedata.normalize("NFD", s) if not unicodedata.combining(c)).lower()


month_by_name = {fold(r["tamil_month"]): i for i, r in enumerate(names["rasi"])}
fest = []
for f in rules["festivals_solar_month_plus_star"]:
    m = f["month"].split(" (")[0]
    fest.append(dict(name=f["name"], month=month_by_name[fold(m)], star=nak_by_iast[f["nakshatra"]]))
wed_months = [month_by_name[fold(m)] for m in wedding["commonly_avoided_tamil_months"]]


grahas, rings = sky["graha"], sky["rings"]


def q(s):
    return json.dumps(s, ensure_ascii=False)


def kt_list(items, fn):
    return ",\n".join("        " + fn(x) for x in items)


header = "// GENERATED by scripts/gen_tables.py from data/names.json, data/rules.json and docs/SPEC.md §3.\n// Do not edit by hand; edit the sources and re-run the script.\n"

kotlin = header + """package org.hora.panchanga.core

data class TithiInfo(val iast: String, val paksha: String, val number: Int, val family: String, val devanagari: String, val auspiciousFor: String)
data class NakshatraInfo(val iast: String, val devanagari: String, val tamil: String, val nature: String, val deity: String, val temperament: String)
data class YogaInfo(val iast: String, val devanagari: String, val shubha: Boolean, val nature: String)
data class KaranaInfo(val iast: String, val devanagari: String, val fixed: Boolean, val symbol: String, val nature: String, val use: String)
data class VaraInfo(val iast: String, val tamil: String, val lord: String, val devanagari: String, val english: String, val nature: String)
data class RasiInfo(val iast: String, val devanagari: String, val tamilMonth: String, val tamilMonthScript: String)
data class NatureInfo(val meaning: String, val uses: String)
data class Festival(val name: String, val tamilMonth: Int, val nakshatra: Int)
data class Graha(val key: String, val iast: String, val english: String, val science: String, val lore: String)
data class RingInfo(val key: String, val iast: String, val english: String, val color: Long)

object Tables {
    /** 0-based index = (tithi number 1..30) - 1 */
    val tithi = listOf(
%s
    )
    val nakshatra = listOf(
%s
    )
    val yoga = listOf(
%s
    )
    /** The 11 distinct karanas; use [karanaOfSlot] for the 60 slots. */
    val karanaKinds = listOf(
%s
    )
    /** slot 0..59 (0-based, = k - 1) -> index into [karanaKinds] */
    val karanaSlot = intArrayOf(%s)
    fun karanaOfSlot(slot: Int): KaranaInfo = karanaKinds[karanaSlot[slot]]
    val vara = listOf(
%s
    )
    val rasi = listOf(
%s
    )
    val samvatsara = listOf(%s)
    val horaChaldean = listOf(%s)
    /** index 0 = Sunday; value = which eighth of daylight (1-based) */
    val rahuKalam = intArrayOf(%s)
    val yamagandam = intArrayOf(%s)
    val kulikai = intArrayOf(%s)
    val natures = mapOf(
%s
    )
    val festivals = listOf(
%s
    )
    val weddingNakshatras = setOf(%s)
    val weddingAvoidMonths = setOf(%s)
    val ashubhaYogas = setOf(%s)
    const val DISCLAIMER = %s
    /** data/glossary.json — every UI term has a plain-language one-liner */
    val glossary = linkedMapOf(
%s
    )
    /** data/sky.json */
    val grahas = listOf(
%s
    )
    val rings = listOf(
%s
    )
    fun graha(key: String) = grahas.first { it.key == key }
    fun ring(key: String) = rings.first { it.key == key }
}
""" % (
    kt_list(tithi, lambda t: f"TithiInfo({q(t['iast'])}, {q(t['paksha'])}, {t['number']}, {q(t['family'])}, {q(t['dev'])}, {q(t['good'])})"),
    kt_list(nak, lambda n: f"NakshatraInfo({q(n['iast'])}, {q(n['dev'])}, {q(n['ta'])}, {q(n['nature'])}, {q(n['deity'])}, {q(n['temper'])})"),
    kt_list(yoga, lambda y: f"YogaInfo({q(y['iast'])}, {q(y['dev'])}, {str(y['shubha']).lower()}, {q(y['nature'])})"),
    kt_list(kinfo.values(), lambda k: f"KaranaInfo({q(k['iast'])}, {q(k['dev'])}, {str(k['fixed']).lower()}, {q(k['animal'])}, {q(k['nature'])}, {q(k['use'])})"),
    ", ".join(map(str, karana_order)),
    kt_list(vara, lambda v: f"VaraInfo({q(v['iast'])}, {q(v['ta'])}, {q(v['lord'])}, {q(v['dev'])}, {q(v['en'])}, {q(v['nature'])})"),
    kt_list(rasi, lambda r: f"RasiInfo({q(r['iast'])}, {q(r['dev'])}, {q(r['month'])}, {q(r['monthTa'])})"),
    ", ".join(q(s) for s in samvat),
    ", ".join(q(s) for s in hora),
    ", ".join(map(str, kala["rahu_kalam"])), ", ".join(map(str, kala["yamagandam"])), ", ".join(map(str, kala["kulikai"])),
    kt_list(nature_uses.items(), lambda kv: f"{q(kv[0])} to NatureInfo({q(kv[1]['meaning'])}, {q(kv[1]['uses'])})"),
    kt_list(fest, lambda f: f"Festival({q(f['name'])}, {f['month']}, {f['star']})"),
    ", ".join(map(str, wedding["favourable_nakshatra"])),
    ", ".join(map(str, wed_months)),
    ", ".join(map(str, sorted(ASUBHA))),
    q(rules["disclaimer"]),
    kt_list(glossary.items(), lambda kv: f"{q(kv[0])} to {q(kv[1])}"),
    kt_list(grahas, lambda g: f"Graha({q(g['key'])}, {q(g['iast'])}, {q(g['english'])}, {q(g['science'])}, {q(g['lore'])})"),
    kt_list(rings, lambda r: f"RingInfo({q(r['key'])}, {q(r['iast'])}, {q(r['english'])}, 0xFF{r['color'][1:]})"),
)


def sw_list(items, fn):
    return ",\n".join("        " + fn(x) for x in items)


swift = header + """
public struct TithiInfo: Sendable { public let iast, paksha: String; public let number: Int; public let family, devanagari, auspiciousFor: String }
public struct NakshatraInfo: Sendable { public let iast, devanagari, tamil, nature, deity, temperament: String }
public struct YogaInfo: Sendable { public let iast, devanagari: String; public let shubha: Bool; public let nature: String }
public struct KaranaInfo: Sendable { public let iast, devanagari: String; public let fixed: Bool; public let symbol, nature, use: String }
public struct VaraInfo: Sendable { public let iast, tamil, lord, devanagari, english, nature: String }
public struct RasiInfo: Sendable { public let iast, devanagari, tamilMonth, tamilMonthScript: String }
public struct NatureInfo: Sendable { public let meaning, uses: String }
public struct Festival: Sendable { public let name: String; public let tamilMonth: Int; public let nakshatra: Int }
public struct Graha: Sendable { public let key, iast, english, science, lore: String }
public struct RingInfo: Sendable { public let key, iast, english: String; public let color: UInt32 }

public enum Tables {
    /// 0-based index = (tithi number 1..30) - 1
    public static let tithi: [TithiInfo] = [
%s
    ]
    public static let nakshatra: [NakshatraInfo] = [
%s
    ]
    public static let yoga: [YogaInfo] = [
%s
    ]
    /// The 11 distinct karanas; use `karanaOfSlot` for the 60 slots.
    public static let karanaKinds: [KaranaInfo] = [
%s
    ]
    /// slot 0..59 (0-based, = k - 1) -> index into `karanaKinds`
    public static let karanaSlot: [Int] = [%s]
    public static func karanaOfSlot(_ slot: Int) -> KaranaInfo { karanaKinds[karanaSlot[slot]] }
    public static let vara: [VaraInfo] = [
%s
    ]
    public static let rasi: [RasiInfo] = [
%s
    ]
    public static let samvatsara: [String] = [%s]
    public static let horaChaldean: [String] = [%s]
    /// index 0 = Sunday; value = which eighth of daylight (1-based)
    public static let rahuKalam: [Int] = [%s]
    public static let yamagandam: [Int] = [%s]
    public static let kulikai: [Int] = [%s]
    public static let natures: [String: NatureInfo] = [
%s
    ]
    public static let festivals: [Festival] = [
%s
    ]
    public static let weddingNakshatras: Set<Int> = [%s]
    public static let weddingAvoidMonths: Set<Int> = [%s]
    public static let ashubhaYogas: Set<Int> = [%s]
    public static let disclaimer = %s
    /// data/glossary.json — every UI term has a plain-language one-liner
    public static let glossary: KeyValuePairs<String, String> = [
%s
    ]
    /// data/sky.json
    public static let grahas: [Graha] = [
%s
    ]
    public static let rings: [RingInfo] = [
%s
    ]
    public static func graha(_ key: String) -> Graha { grahas.first { $0.key == key }! }
    public static func ring(_ key: String) -> RingInfo { rings.first { $0.key == key }! }
}
""" % (
    sw_list(tithi, lambda t: f"TithiInfo(iast: {q(t['iast'])}, paksha: {q(t['paksha'])}, number: {t['number']}, family: {q(t['family'])}, devanagari: {q(t['dev'])}, auspiciousFor: {q(t['good'])})"),
    sw_list(nak, lambda n: f"NakshatraInfo(iast: {q(n['iast'])}, devanagari: {q(n['dev'])}, tamil: {q(n['ta'])}, nature: {q(n['nature'])}, deity: {q(n['deity'])}, temperament: {q(n['temper'])})"),
    sw_list(yoga, lambda y: f"YogaInfo(iast: {q(y['iast'])}, devanagari: {q(y['dev'])}, shubha: {str(y['shubha']).lower()}, nature: {q(y['nature'])})"),
    sw_list(kinfo.values(), lambda k: f"KaranaInfo(iast: {q(k['iast'])}, devanagari: {q(k['dev'])}, fixed: {str(k['fixed']).lower()}, symbol: {q(k['animal'])}, nature: {q(k['nature'])}, use: {q(k['use'])})"),
    ", ".join(map(str, karana_order)),
    sw_list(vara, lambda v: f"VaraInfo(iast: {q(v['iast'])}, tamil: {q(v['ta'])}, lord: {q(v['lord'])}, devanagari: {q(v['dev'])}, english: {q(v['en'])}, nature: {q(v['nature'])})"),
    sw_list(rasi, lambda r: f"RasiInfo(iast: {q(r['iast'])}, devanagari: {q(r['dev'])}, tamilMonth: {q(r['month'])}, tamilMonthScript: {q(r['monthTa'])})"),
    ", ".join(q(s) for s in samvat),
    ", ".join(q(s) for s in hora),
    ", ".join(map(str, kala["rahu_kalam"])), ", ".join(map(str, kala["yamagandam"])), ", ".join(map(str, kala["kulikai"])),
    sw_list(nature_uses.items(), lambda kv: f"{q(kv[0])}: NatureInfo(meaning: {q(kv[1]['meaning'])}, uses: {q(kv[1]['uses'])})"),
    sw_list(fest, lambda f: f"Festival(name: {q(f['name'])}, tamilMonth: {f['month']}, nakshatra: {f['star']})"),
    ", ".join(map(str, wedding["favourable_nakshatra"])),
    ", ".join(map(str, wed_months)),
    ", ".join(map(str, sorted(ASUBHA))),
    q(rules["disclaimer"]),
    sw_list(glossary.items(), lambda kv: f"{q(kv[0])}: {q(kv[1])}"),
    sw_list(grahas, lambda g: f"Graha(key: {q(g['key'])}, iast: {q(g['iast'])}, english: {q(g['english'])}, science: {q(g['science'])}, lore: {q(g['lore'])})"),
    sw_list(rings, lambda r: f"RingInfo(key: {q(r['key'])}, iast: {q(r['iast'])}, english: {q(r['english'])}, color: 0x{r['color'][1:]})"),
)

for path, text in [("android/core/src/main/kotlin/org/hora/panchanga/core/Tables.kt", kotlin),
                   ("ios/PanchangaCore/Sources/PanchangaCore/Tables.swift", swift)]:
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote", path)

# data/stars.json ships as-is inside both apps
import shutil
for dst in ["android/app/src/main/assets/stars.json", "ios/PanchangaClock/Resources/Data/stars.json"]:
    os.makedirs(os.path.dirname(os.path.join(ROOT, dst)), exist_ok=True)
    shutil.copyfile(os.path.join(ROOT, "data/stars.json"), os.path.join(ROOT, dst))
    print("copied", dst)
