// GENERATED by scripts/gen_tables.py from data/names.json, data/rules.json and docs/SPEC.md §3.
// Do not edit by hand; edit the sources and re-run the script.

public struct TithiInfo: Sendable { public let iast, paksha: String; public let number: Int; public let family, devanagari, auspiciousFor: String }
public struct NakshatraInfo: Sendable { public let iast, devanagari, tamil, nature, deity, temperament: String }
public struct YogaInfo: Sendable { public let iast, devanagari: String; public let shubha: Bool; public let nature: String }
public struct KaranaInfo: Sendable { public let iast, devanagari: String; public let fixed: Bool; public let symbol, nature, use: String }
public struct VaraInfo: Sendable { public let iast, tamil, lord, devanagari, english, nature: String }
public struct RasiInfo: Sendable { public let iast, devanagari, tamilMonth, tamilMonthScript: String }
public struct NatureInfo: Sendable { public let meaning, uses: String }
public struct Festival: Sendable { public let name: String; public let tamilMonth: Int; public let nakshatra: Int }
public struct Graha: Sendable { public let key, iast, english, science, lore: String }
public struct RingInfo: Sendable { public let key, iast, english: String; public let color: UInt32 }

public enum Tables {
    /// 0-based index = (tithi number 1..30) - 1
    public static let tithi: [TithiInfo] = [
        TithiInfo(iast: "Pratipadā", paksha: "Śukla", number: 1, family: "Nandā", devanagari: "प्रतिपदा", auspiciousFor: "Beginnings, new projects, fine arts"),
        TithiInfo(iast: "Dvitīyā", paksha: "Śukla", number: 2, family: "Bhadrā", devanagari: "द्वितीया", auspiciousFor: "Education, commerce, marriage, journeys"),
        TithiInfo(iast: "Tṛtīyā", paksha: "Śukla", number: 3, family: "Jayā", devanagari: "तृतीया", auspiciousFor: "Legal actions, competitions, overcoming hurdles"),
        TithiInfo(iast: "Caturthī", paksha: "Śukla", number: 4, family: "Riktā", devanagari: "चतुर्थी", auspiciousFor: "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo(iast: "Pañcamī", paksha: "Śukla", number: 5, family: "Pūrṇā", devanagari: "पंचमी", auspiciousFor: "High-impact initiatives, rituals, real estate"),
        TithiInfo(iast: "Ṣaṣṭhī", paksha: "Śukla", number: 6, family: "Nandā", devanagari: "षष्ठी", auspiciousFor: "Celebrations, beginnings, fine arts"),
        TithiInfo(iast: "Saptamī", paksha: "Śukla", number: 7, family: "Bhadrā", devanagari: "सप्तमी", auspiciousFor: "Education, commerce, marriage, journeys"),
        TithiInfo(iast: "Aṣṭamī", paksha: "Śukla", number: 8, family: "Jayā", devanagari: "अष्टमी", auspiciousFor: "Legal actions, competitions, overcoming hurdles"),
        TithiInfo(iast: "Navamī", paksha: "Śukla", number: 9, family: "Riktā", devanagari: "नवमी", auspiciousFor: "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo(iast: "Daśamī", paksha: "Śukla", number: 10, family: "Pūrṇā", devanagari: "दशमी", auspiciousFor: "High-impact initiatives, rituals, real estate"),
        TithiInfo(iast: "Ekādaśī", paksha: "Śukla", number: 11, family: "Nandā", devanagari: "एकादशी", auspiciousFor: "Celebrations, beginnings, fine arts"),
        TithiInfo(iast: "Dvādaśī", paksha: "Śukla", number: 12, family: "Bhadrā", devanagari: "द्वादशी", auspiciousFor: "Education, commerce, marriage, journeys"),
        TithiInfo(iast: "Trayodaśī", paksha: "Śukla", number: 13, family: "Jayā", devanagari: "त्रयोदशी", auspiciousFor: "Legal actions, competitions, overcoming hurdles"),
        TithiInfo(iast: "Caturdaśī", paksha: "Śukla", number: 14, family: "Riktā", devanagari: "चतुर्दशी", auspiciousFor: "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo(iast: "Pūrṇimā", paksha: "Śukla", number: 15, family: "Pūrṇā", devanagari: "पूर्णिमा", auspiciousFor: "High-impact initiatives, rituals, real estate"),
        TithiInfo(iast: "Pratipadā", paksha: "Kṛṣṇa", number: 1, family: "Nandā", devanagari: "प्रतिपदा", auspiciousFor: "Beginnings, new projects, fine arts"),
        TithiInfo(iast: "Dvitīyā", paksha: "Kṛṣṇa", number: 2, family: "Bhadrā", devanagari: "द्वितीया", auspiciousFor: "Education, commerce, marriage, journeys"),
        TithiInfo(iast: "Tṛtīyā", paksha: "Kṛṣṇa", number: 3, family: "Jayā", devanagari: "तृतीया", auspiciousFor: "Legal actions, competitions, overcoming hurdles"),
        TithiInfo(iast: "Caturthī", paksha: "Kṛṣṇa", number: 4, family: "Riktā", devanagari: "चतुर्थी", auspiciousFor: "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo(iast: "Pañcamī", paksha: "Kṛṣṇa", number: 5, family: "Pūrṇā", devanagari: "पंचमी", auspiciousFor: "High-impact initiatives, rituals, real estate"),
        TithiInfo(iast: "Ṣaṣṭhī", paksha: "Kṛṣṇa", number: 6, family: "Nandā", devanagari: "षष्ठी", auspiciousFor: "Celebrations, beginnings, fine arts"),
        TithiInfo(iast: "Saptamī", paksha: "Kṛṣṇa", number: 7, family: "Bhadrā", devanagari: "सप्तमी", auspiciousFor: "Education, commerce, marriage, journeys"),
        TithiInfo(iast: "Aṣṭamī", paksha: "Kṛṣṇa", number: 8, family: "Jayā", devanagari: "अष्टमी", auspiciousFor: "Legal actions, competitions, overcoming hurdles"),
        TithiInfo(iast: "Navamī", paksha: "Kṛṣṇa", number: 9, family: "Riktā", devanagari: "नवमी", auspiciousFor: "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo(iast: "Daśamī", paksha: "Kṛṣṇa", number: 10, family: "Pūrṇā", devanagari: "दशमी", auspiciousFor: "High-impact initiatives, rituals, real estate"),
        TithiInfo(iast: "Ekādaśī", paksha: "Kṛṣṇa", number: 11, family: "Nandā", devanagari: "एकादशी", auspiciousFor: "Celebrations, beginnings, fine arts"),
        TithiInfo(iast: "Dvādaśī", paksha: "Kṛṣṇa", number: 12, family: "Bhadrā", devanagari: "द्वादशी", auspiciousFor: "Education, commerce, marriage, journeys"),
        TithiInfo(iast: "Trayodaśī", paksha: "Kṛṣṇa", number: 13, family: "Jayā", devanagari: "त्रयोदशी", auspiciousFor: "Legal actions, competitions, overcoming hurdles"),
        TithiInfo(iast: "Caturdaśī", paksha: "Kṛṣṇa", number: 14, family: "Riktā", devanagari: "चतुर्दशी", auspiciousFor: "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo(iast: "Amāvāsyā", paksha: "Kṛṣṇa", number: 15, family: "Pūrṇā", devanagari: "अमावस्या", auspiciousFor: "High-impact initiatives, rituals, real estate")
    ]
    public static let nakshatra: [NakshatraInfo] = [
        NakshatraInfo(iast: "Aśvinī", devanagari: "अश्विनी", tamil: "அசுவினி", nature: "ksipra", deity: "Ashvins (Divine Twins)", temperament: "Swift, Healing"),
        NakshatraInfo(iast: "Bharaṇī", devanagari: "भरणी", tamil: "பரணி", nature: "ugra", deity: "Yama (God of Death)", temperament: "Fierce, Restrictive"),
        NakshatraInfo(iast: "Kṛttikā", devanagari: "कृत्तिका", tamil: "கார்த்திகை", nature: "misra", deity: "Agni (Fire God)", temperament: "Mixed, Sharp"),
        NakshatraInfo(iast: "Rohiṇī", devanagari: "रोहिणी", tamil: "ரோகிணி", nature: "dhruva", deity: "Prajapati (Creator)", temperament: "Fixed, Fertile"),
        NakshatraInfo(iast: "Mṛgaśīrṣa", devanagari: "मृगशीर्ष", tamil: "மிருகசீரிடம்", nature: "mrdu", deity: "Soma (Moon)", temperament: "Gentle, Inquisitive"),
        NakshatraInfo(iast: "Ārdrā", devanagari: "आर्द्रा", tamil: "திருவாதிரை", nature: "tiksna", deity: "Rudra (Storm God)", temperament: "Sharp, Transformative"),
        NakshatraInfo(iast: "Punarvasu", devanagari: "पुनर्वसु", tamil: "புனர்பூசம்", nature: "cara", deity: "Aditi (Mother of Gods)", temperament: "Movable, Renewing"),
        NakshatraInfo(iast: "Puṣya", devanagari: "पुष्य", tamil: "பூசம்", nature: "ksipra", deity: "Brihaspati (Jupiter)", temperament: "Swift, Nourishing"),
        NakshatraInfo(iast: "Āśleṣā", devanagari: "आश्लेषा", tamil: "ஆயில்யம்", nature: "tiksna", deity: "Sarpas (Serpents)", temperament: "Sharp, Piercing"),
        NakshatraInfo(iast: "Maghā", devanagari: "मघा", tamil: "மகம்", nature: "ugra", deity: "Pitris (Ancestors)", temperament: "Fierce, Royal"),
        NakshatraInfo(iast: "Pūrva Phalgunī", devanagari: "पूर्वफल्गुनी", tamil: "பூரம்", nature: "ugra", deity: "Bhaga (God of Prosperity)", temperament: "Fierce, Creative"),
        NakshatraInfo(iast: "Uttara Phalgunī", devanagari: "उत्तरफल्गुनी", tamil: "உத்திரம்", nature: "dhruva", deity: "Aryaman (God of Patronage)", temperament: "Fixed, Enduring"),
        NakshatraInfo(iast: "Hasta", devanagari: "हस्त", tamil: "அஸ்தம்", nature: "ksipra", deity: "Savitr (Sun God)", temperament: "Swift, Dexterous"),
        NakshatraInfo(iast: "Citrā", devanagari: "चित्रा", tamil: "சித்திரை", nature: "mrdu", deity: "Tvashtar (Divine Architect)", temperament: "Gentle, Artistic"),
        NakshatraInfo(iast: "Svātī", devanagari: "स्वाती", tamil: "சுவாதி", nature: "cara", deity: "Vayu (Wind God)", temperament: "Movable, Adaptable"),
        NakshatraInfo(iast: "Viśākhā", devanagari: "विशाखा", tamil: "விசாகம்", nature: "misra", deity: "Indragni (Indra+Agni)", temperament: "Mixed, Purpose-Driven"),
        NakshatraInfo(iast: "Anurādhā", devanagari: "अनुराधा", tamil: "அனுஷம்", nature: "mrdu", deity: "Mitra (Divine Friend)", temperament: "Gentle, Devotional"),
        NakshatraInfo(iast: "Jyeṣṭhā", devanagari: "ज्येष्ठा", tamil: "கேட்டை", nature: "tiksna", deity: "Indra (King of Gods)", temperament: "Sharp, Protective"),
        NakshatraInfo(iast: "Mūla", devanagari: "मूल", tamil: "மூலம்", nature: "tiksna", deity: "Nirriti (Goddess of Destruction)", temperament: "Sharp, Investigating"),
        NakshatraInfo(iast: "Pūrva Āṣāḍhā", devanagari: "पूर्वाषाढा", tamil: "பூராடம்", nature: "ugra", deity: "Apas (Waters)", temperament: "Fierce, Invincible"),
        NakshatraInfo(iast: "Uttara Āṣāḍhā", devanagari: "उत्तराषाढा", tamil: "உத்திராடம்", nature: "dhruva", deity: "Vishvedevas (All Gods)", temperament: "Fixed, Victorious"),
        NakshatraInfo(iast: "Śravaṇa", devanagari: "श्रवण", tamil: "திருவோணம்", nature: "cara", deity: "Vishnu (Preserver)", temperament: "Movable, Receptive"),
        NakshatraInfo(iast: "Dhaniṣṭhā", devanagari: "धनिष्ठा", tamil: "அவிட்டம்", nature: "cara", deity: "Ashta Vasus (Eight Deities)", temperament: "Movable, Rhythmic"),
        NakshatraInfo(iast: "Śatabhiṣaj", devanagari: "शतभिषक्", tamil: "சதயம்", nature: "cara", deity: "Varuna (God of Waters)", temperament: "Movable, Curative"),
        NakshatraInfo(iast: "Pūrva Bhādrapadā", devanagari: "पूर्वभाद्रपदा", tamil: "பூரட்டாதி", nature: "ugra", deity: "Aja Ekapada (One-footed Goat)", temperament: "Fierce, Ascetic"),
        NakshatraInfo(iast: "Uttara Bhādrapadā", devanagari: "उत्तरभाद्रपदा", tamil: "உத்திரட்டாதி", nature: "dhruva", deity: "Ahirbudhnya (Serpent Dragon)", temperament: "Fixed, Grounded"),
        NakshatraInfo(iast: "Revatī", devanagari: "रेवती", tamil: "ரேவதி", nature: "mrdu", deity: "Pushan (Nourisher)", temperament: "Gentle, Nurturing")
    ]
    public static let yoga: [YogaInfo] = [
        YogaInfo(iast: "Viṣkambha", devanagari: "विष्कम्भ", shubha: false, nature: "Obstruction, initial friction"),
        YogaInfo(iast: "Prīti", devanagari: "प्रीति", shubha: true, nature: "Love, affection, satisfaction"),
        YogaInfo(iast: "Āyuṣmān", devanagari: "आयुष्मान", shubha: true, nature: "Long life, vitality, good health"),
        YogaInfo(iast: "Saubhāgya", devanagari: "सौभाग्य", shubha: true, nature: "Good fortune, prosperity, auspiciousness"),
        YogaInfo(iast: "Śobhana", devanagari: "शोभन", shubha: true, nature: "Beautiful, splendid, virtuous"),
        YogaInfo(iast: "Atigaṇḍa", devanagari: "अतिगण्ड", shubha: false, nature: "Severe complications, high turbulence"),
        YogaInfo(iast: "Sukarmā", devanagari: "सुकर्मा", shubha: true, nature: "Good actions, virtuous deeds, merit"),
        YogaInfo(iast: "Dhṛti", devanagari: "धृति", shubha: true, nature: "Steadfastness, patience, determination"),
        YogaInfo(iast: "Śūla", devanagari: "शूल", shubha: false, nature: "Sharp conflict, pain, weapons, surgery"),
        YogaInfo(iast: "Gaṇḍa", devanagari: "गण्ड", shubha: false, nature: "Emotional knots, tangles, administrative blocks"),
        YogaInfo(iast: "Vṛddhi", devanagari: "वृद्धि", shubha: true, nature: "Growth, increase, prosperity, expansion"),
        YogaInfo(iast: "Dhruva", devanagari: "ध्रुव", shubha: true, nature: "Fixed, stable, permanent, unchanging"),
        YogaInfo(iast: "Vyāghāta", devanagari: "व्याघात", shubha: false, nature: "Threatening, destructive, prone to sudden injury"),
        YogaInfo(iast: "Harṣaṇa", devanagari: "हर्षण", shubha: true, nature: "Joy, delight, happiness, celebration"),
        YogaInfo(iast: "Vajra", devanagari: "वज्र", shubha: false, nature: "Volatile, piercing, sharp like thunderbolt"),
        YogaInfo(iast: "Siddhi", devanagari: "सिद्धि", shubha: true, nature: "Accomplishment, perfection, attainment"),
        YogaInfo(iast: "Vyatīpāta", devanagari: "व्यतिपात", shubha: false, nature: "Major directional calamity; avoid material initiatives"),
        YogaInfo(iast: "Varīyān", devanagari: "वरियान्", shubha: true, nature: "Excellent, best, superior quality"),
        YogaInfo(iast: "Parigha", devanagari: "परिघ", shubha: false, nature: "Gates/barriers, delays, opposition, obstacles"),
        YogaInfo(iast: "Śiva", devanagari: "शिव", shubha: true, nature: "Auspicious, benevolent, benevolent destruction"),
        YogaInfo(iast: "Siddha", devanagari: "सिद्ध", shubha: true, nature: "Perfected, accomplished, established"),
        YogaInfo(iast: "Sādhya", devanagari: "साध्य", shubha: true, nature: "Attainable, possible, achievable"),
        YogaInfo(iast: "Śubha", devanagari: "शुभ", shubha: true, nature: "Auspicious, favorable, beneficial"),
        YogaInfo(iast: "Śukla", devanagari: "शुक्ल", shubha: true, nature: "Bright, pure, clear, white"),
        YogaInfo(iast: "Brahma", devanagari: "ब्रह्म", shubha: true, nature: "Creative, expansive, universal consciousness"),
        YogaInfo(iast: "Aindra", devanagari: "इन्द्र", shubha: true, nature: "Power, leadership, sovereignty, strength"),
        YogaInfo(iast: "Vaidhṛti", devanagari: "वैधृति", shubha: false, nature: "Chaotic dissipation; unstable for worldly investments")
    ]
    /// The 11 distinct karanas; use `karanaOfSlot` for the 60 slots.
    public static let karanaKinds: [KaranaInfo] = [
        KaranaInfo(iast: "Kiṃstughna", devanagari: "किंस्तुघ्न", fixed: true, symbol: "Wild Beast", nature: "Rebirth, Foundational", use: "Sowing seeds, charity, foundation stones"),
        KaranaInfo(iast: "Bava", devanagari: "बव", fixed: false, symbol: "Lion", nature: "Commanding, Courageous", use: "Leadership, fitness, health, initiation"),
        KaranaInfo(iast: "Bālava", devanagari: "बालव", fixed: false, symbol: "Tiger / Leopard", nature: "Intellectual, Active", use: "Study, spiritual rituals, sacred tasks"),
        KaranaInfo(iast: "Kaulava", devanagari: "कौलव", fixed: false, symbol: "Boar / Pig", nature: "Cooperative, Grounded", use: "Social alliances, contracts, partnerships"),
        KaranaInfo(iast: "Taitila", devanagari: "तैतिल", fixed: false, symbol: "Rhinoceros", nature: "Defensive, Resilient", use: "Construction, official paperwork, boundaries"),
        KaranaInfo(iast: "Gara", devanagari: "गर", fixed: false, symbol: "Elephant", nature: "Diligent, Heavy", use: "Agriculture, groundwork, physical labor"),
        KaranaInfo(iast: "Vaṇij", devanagari: "वणिज", fixed: false, symbol: "Merchant", nature: "Commercial, Agile", use: "Trade, financial exchanges, sales trips"),
        KaranaInfo(iast: "Viṣṭi", devanagari: "विष्टि", fixed: false, symbol: "Donkey", nature: "Volatile, Destructive", use: "avoid all auspicious events"),
        KaranaInfo(iast: "Śakuni", devanagari: "शकुनि", fixed: true, symbol: "Raven / Bird", nature: "Diagnostic, Remedial", use: "Medicine, therapy, settling long disputes"),
        KaranaInfo(iast: "Catuṣpāda", devanagari: "चतुष्पाद", fixed: true, symbol: "Bull / Quadruped", nature: "Grounded, Material", use: "Ancestral rites (Shraddha), animal care, soil"),
        KaranaInfo(iast: "Nāga", devanagari: "नाग", fixed: true, symbol: "Serpent", nature: "Covert, Penetrating", use: "Mining, excavations, secret negotiations")
    ]
    /// slot 0..59 (0-based, = k - 1) -> index into `karanaKinds`
    public static let karanaSlot: [Int] = [0, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    public static func karanaOfSlot(_ slot: Int) -> KaranaInfo { karanaKinds[karanaSlot[slot]] }
    public static let vara: [VaraInfo] = [
        VaraInfo(iast: "Ravivāra", tamil: "ஞாயிறு", lord: "Sūrya", devanagari: "रविवार", english: "Sunday", nature: "Vitality, leadership, authority"),
        VaraInfo(iast: "Somavāra", tamil: "திங்கள்", lord: "Candra", devanagari: "सोमवार", english: "Monday", nature: "Mind, emotions, nurturing"),
        VaraInfo(iast: "Maṅgalavāra", tamil: "செவ்வாய்", lord: "Maṅgala", devanagari: "मङ्गलवार", english: "Tuesday", nature: "Energy, courage, conflict"),
        VaraInfo(iast: "Budhavāra", tamil: "புதன்", lord: "Budha", devanagari: "बुधवार", english: "Wednesday", nature: "Intellect, communication, trade"),
        VaraInfo(iast: "Guruvāra", tamil: "வியாழன்", lord: "Guru", devanagari: "गुरुवार", english: "Thursday", nature: "Wisdom, expansion, prosperity"),
        VaraInfo(iast: "Śukravāra", tamil: "வெள்ளி", lord: "Śukra", devanagari: "शुक्रवार", english: "Friday", nature: "Love, beauty, creativity, luxury"),
        VaraInfo(iast: "Śanivāra", tamil: "சனி", lord: "Śani", devanagari: "शनिवार", english: "Saturday", nature: "Discipline, karma, longevity, obstacles")
    ]
    public static let rasi: [RasiInfo] = [
        RasiInfo(iast: "Meṣa", devanagari: "मेष", tamilMonth: "Chithirai", tamilMonthScript: "சித்திரை"),
        RasiInfo(iast: "Vṛṣabha", devanagari: "वृषभ", tamilMonth: "Vaikāsi", tamilMonthScript: "வைகாசி"),
        RasiInfo(iast: "Mithuna", devanagari: "मिथुन", tamilMonth: "Āni", tamilMonthScript: "ஆனி"),
        RasiInfo(iast: "Karkaṭa", devanagari: "कर्कट", tamilMonth: "Āḍi", tamilMonthScript: "ஆடி"),
        RasiInfo(iast: "Siṃha", devanagari: "सिंह", tamilMonth: "Āvaṇi", tamilMonthScript: "ஆவணி"),
        RasiInfo(iast: "Kanyā", devanagari: "कन्या", tamilMonth: "Puraṭṭāsi", tamilMonthScript: "புரட்டாசி"),
        RasiInfo(iast: "Tulā", devanagari: "तुला", tamilMonth: "Aippasi", tamilMonthScript: "ஐப்பசி"),
        RasiInfo(iast: "Vṛścika", devanagari: "वृश्चिक", tamilMonth: "Kārttikai", tamilMonthScript: "கார்த்திகை"),
        RasiInfo(iast: "Dhanus", devanagari: "धनुस्", tamilMonth: "Mārgazhi", tamilMonthScript: "மார்கழி"),
        RasiInfo(iast: "Makara", devanagari: "मकर", tamilMonth: "Thai", tamilMonthScript: "தை"),
        RasiInfo(iast: "Kumbha", devanagari: "कुम्भ", tamilMonth: "Māsi", tamilMonthScript: "மாசி"),
        RasiInfo(iast: "Mīna", devanagari: "मीन", tamilMonth: "Panguni", tamilMonthScript: "பங்குனி")
    ]
    public static let samvatsara: [String] = ["Prabhava", "Vibhava", "Śukla", "Pramoda", "Prajāpati", "Āṅgīrasa", "Śrīmukha", "Bhāva", "Yuvan", "Dhātṛ", "Īśvara", "Bahudhānya", "Pramāthin", "Vikrama", "Vṛṣa", "Citrabhānu", "Svabhānu", "Tāraṇa", "Pārthiva", "Vyaya", "Sarvajit", "Sarvadhārin", "Virodhin", "Vikṛti", "Khara", "Nandana", "Vijaya", "Jaya", "Manmatha", "Durmukha", "Hemalamba", "Vilamba", "Vikārin", "Śārvari", "Plava", "Śubhakṛt", "Śobhakṛt", "Krodhin", "Viśvāvasu", "Parābhava", "Plavaṅga", "Kīlaka", "Saumya", "Sādhāraṇa", "Virodhikṛt", "Paridhāvin", "Pramādin", "Ānanda", "Rākṣasa", "Nala", "Piṅgala", "Kālayukta", "Siddhārthin", "Raudra", "Durmati", "Dundubhi", "Rudhirodgārin", "Raktākṣin", "Krodhana", "Akṣaya"]
    public static let horaChaldean: [String] = ["Śani", "Guru", "Maṅgala", "Sūrya", "Śukra", "Budha", "Candra"]
    /// index 0 = Sunday; value = which eighth of daylight (1-based)
    public static let rahuKalam: [Int] = [8, 2, 7, 5, 6, 4, 3]
    public static let yamagandam: [Int] = [5, 4, 3, 2, 1, 7, 6]
    public static let kulikai: [Int] = [7, 6, 5, 4, 3, 2, 1]
    public static let natures: [String: NatureInfo] = [
        "dhruva": NatureInfo(meaning: "fixed", uses: "foundations, house-warming (gṛhapraveśa), planting"),
        "cara": NatureInfo(meaning: "movable", uses: "travel, vehicles"),
        "ksipra": NatureInfo(meaning: "swift", uses: "learning, medicine, trade"),
        "mrdu": NatureInfo(meaning: "soft", uses: "arts, friendship, new clothes"),
        "ugra": NatureInfo(meaning: "fierce", uses: "avoided for gentle work"),
        "tiksna": NatureInfo(meaning: "sharp", uses: "avoided for gentle work"),
        "misra": NatureInfo(meaning: "mixed", uses: "routine work")
    ]
    public static let festivals: [Festival] = [
        Festival(name: "Kārttikai Dīpam", tamilMonth: 7, nakshatra: 2),
        Festival(name: "Thai Pūsam", tamilMonth: 9, nakshatra: 7),
        Festival(name: "Paṅguni Uttiram", tamilMonth: 11, nakshatra: 11),
        Festival(name: "Vaikāsi Visākam", tamilMonth: 1, nakshatra: 15)
    ]
    public static let weddingNakshatras: Set<Int> = [3, 4, 9, 11, 12, 14, 16, 18, 20, 25, 26]
    public static let weddingAvoidMonths: Set<Int> = [3, 5, 8]
    public static let ashubhaYogas: Set<Int> = [1, 6, 9, 10, 13, 15, 17, 19, 27]
    public static let disclaimer = "Teaching-level rules used in the film. Real muhūrta selection also weighs lagna, tārābalam, candrabalam, month and personal charts; present results as guidance."
    /// data/glossary.json — every UI term has a plain-language one-liner
    public static let glossary: KeyValuePairs<String, String> = [
        "Pañcāṅga": "\"Five limbs\" — the almanac of vāra, tithi, nakṣatra, yoga and karaṇa, all read from the Sun and Moon.",
        "Vāra": "The weekday. In the Tamil convention it changes at sunrise, not midnight, and is named for the planet ruling its first horā.",
        "Tithi": "A lunar day: each 12° the Moon gains on the Sun. Thirty tithis make one synodic month.",
        "Pakṣa": "A fortnight. Śukla (bright, waxing) runs to Pūrṇimā; Kṛṣṇa (dark, waning) runs to Amāvāsyā.",
        "Śukla": "The bright, waxing fortnight — tithis 1 to 15, ending at the full moon.",
        "Kṛṣṇa": "The dark, waning fortnight — tithis 16 to 30, ending at the new moon.",
        "Pūrṇimā": "Full moon: the 15th tithi, when the Moon is 168°–180° from the Sun.",
        "Amāvāsyā": "New moon: the 30th tithi, when the Moon closes the last 12° on the Sun.",
        "Nakṣatra": "A lunar mansion: one of 27 equal stretches of 13°20′ along the ecliptic. The Moon crosses one in about a day.",
        "Pada": "A quarter of a nakṣatra (3°20′). 27 × 4 = 108 padas circle the sky.",
        "Yoga": "The sum of the Sun's and Moon's longitudes, divided into 27 parts of 13°20′. Nine of the 27 are considered aśubha.",
        "Karaṇa": "Half a tithi (6° of elongation). 60 slots per month: seven movable names cycle eight times, plus four fixed ones.",
        "Viṣṭi": "Also called Bhadrā — the one movable karaṇa that is avoided for auspicious beginnings.",
        "Śubha": "Auspicious, favourable.",
        "Aśubha": "Inauspicious — traditionally avoided for new undertakings.",
        "Nāḻigai": "The Tamil ghaṭikā: 1/60 of a day, 24 minutes. The day is counted in nāḻigai from sunrise.",
        "Vināḻigai": "1/60 of a nāḻigai — 24 seconds.",
        "Muhūrta": "Two nāḻigai (48 minutes); also an auspicious window chosen for an event. Always guidance, never a guarantee.",
        "Abhijit": "The 8th of the 15 daytime muhūrtas, around local noon — widely held auspicious.",
        "Rāhu kālam": "One eighth of daylight, chosen by weekday, traditionally avoided for beginnings.",
        "Yamagaṇḍam": "Another eighth of daylight by weekday, avoided for beginnings.",
        "Kuḷikai": "The eighth of daylight ruled by Gulika (Śani's son); work begun in it is said to repeat.",
        "Horā": "One of 24 planetary hours per day, lords in Chaldean order: Śani, Guru, Maṅgala, Sūrya, Śukra, Budha, Candra.",
        "Rāśi": "One of the 12 sidereal signs of 30°. The Sun's rāśi names the Tamil solar month.",
        "Ayanāṁśa": "The offset between the tropical and sidereal zodiacs (Lahiri: about 24°14′ in 2026), from the precession of the equinoxes.",
        "Nirayana": "Sidereal — longitudes measured from the fixed stars (Spica at 180°), not the moving equinox.",
        "Elongation": "E = λ☾ − λ☉: how far the Moon is ahead of the Sun. It sets both the tithi and the Moon's phase.",
        "Ecliptic": "The Sun's yearly path across the stars. The Moon is never more than about 5° from it.",
        "Saṃvatsara": "The year name in the 60-year Jovian cycle. The Tamil year begins in Chithirai.",
        "Saṅkrānti": "The moment the Sun enters a new rāśi — the start of a Tamil solar month.",
        "Kṣaya": "A tithi that begins and ends between two sunrises, so no day is named for it.",
        "Adhika": "A tithi that is in force at two successive sunrises, so two days share its name.",
        "Candrāṣṭamam": "Days when the Moon is in the 8th rāśi from one's birth rāśi; avoided for important work.",
        "Graha": "A 'seizer' — the visible planets, Sun and Moon, plus the lunar nodes Rāhu and Ketu."
    ]
    /// data/sky.json
    public static let grahas: [Graha] = [
        Graha(key: "sun", iast: "Sūrya", english: "Sun", science: "A G2 star 1 AU away; its path against the stars is the ecliptic.", lore: "Soul and sovereignty; lord of Ravivāra and of Siṃha."),
        Graha(key: "moon", iast: "Candra", english: "Moon", science: "Earth's satellite, 384,400 km away; laps the zodiac in 27.3 days.", lore: "Mind and emotion; lord of Somavāra and of Karkaṭa."),
        Graha(key: "mercury", iast: "Budha", english: "Mercury", science: "Innermost planet; never strays more than 28° from the Sun.", lore: "Intellect and speech; lord of Budhavāra, Mithuna and Kanyā."),
        Graha(key: "venus", iast: "Śukra", english: "Venus", science: "Brightest planet, wrapped in sulphuric cloud; within 47° of the Sun.", lore: "Beauty, art and pleasure; lord of Śukravāra, Vṛṣabha and Tulā."),
        Graha(key: "mars", iast: "Maṅgala", english: "Mars", science: "The red planet; its retrograde loops puzzled every early astronomer.", lore: "Courage and conflict; lord of Maṅgalavāra, Meṣa and Vṛścika."),
        Graha(key: "jupiter", iast: "Guru", english: "Jupiter", science: "The giant; spends about a year in each rāśi, which names the 60-year cycle.", lore: "Wisdom and the teacher of the gods; lord of Guruvāra, Dhanus and Mīna."),
        Graha(key: "saturn", iast: "Śani", english: "Saturn", science: "Ringed and slow: 29.5 years round the zodiac, about 2½ years per rāśi.", lore: "Time, discipline and karma; lord of Śanivāra, Makara and Kumbha."),
        Graha(key: "rahu", iast: "Rāhu", english: "North lunar node", science: "Where the Moon's orbit crosses the ecliptic going north; eclipses happen near the nodes.", lore: "The shadow graha said to swallow the Sun and Moon at eclipses."),
        Graha(key: "ketu", iast: "Ketu", english: "South lunar node", science: "Always opposite Rāhu; the nodes drift backwards once round in 18.6 years.", lore: "The headless body of the demon; detachment and liberation."),
        Graha(key: "earth", iast: "Pṛthvī", english: "Earth", science: "The observer's home: every limb is measured from here.", lore: "Bhūmi Devī, the goddess who bears all.")
    ]
    public static let rings: [RingInfo] = [
        RingInfo(key: "nazhigai", iast: "Nāḻigai", english: "Hour dial — 60 per day from sunrise", color: 0xE3AE4A),
        RingInfo(key: "nakshatra", iast: "Nakṣatra", english: "Lunar mansions — Moon among the stars", color: 0x5B8DEF),
        RingInfo(key: "tithi", iast: "Tithi", english: "Lunar day — Moon's lead on the Sun", color: 0xCBD5DE),
        RingInfo(key: "yoga", iast: "Yoga", english: "Union — Sun + Moon", color: 0x63B8B2),
        RingInfo(key: "karana", iast: "Karaṇa", english: "Half lunar day", color: 0xC07A43),
        RingInfo(key: "vara", iast: "Vāra", english: "Weekday", color: 0xF3D491),
        RingInfo(key: "rasi", iast: "Rāśi", english: "Zodiac sign", color: 0xE3AE4A)
    ]
    public static func graha(_ key: String) -> Graha { grahas.first { $0.key == key }! }
    public static func ring(_ key: String) -> RingInfo { rings.first { $0.key == key }! }
}
