// GENERATED by scripts/gen_tables.py from data/names.json, data/rules.json and docs/SPEC.md §3.
// Do not edit by hand; edit the sources and re-run the script.
package org.hora.panchanga.core

data class TithiInfo(val iast: String, val paksha: String, val number: Int, val family: String, val devanagari: String, val auspiciousFor: String)
data class NakshatraInfo(val iast: String, val devanagari: String, val tamil: String, val nature: String, val deity: String, val temperament: String)
data class YogaInfo(val iast: String, val devanagari: String, val shubha: Boolean, val nature: String)
data class KaranaInfo(val iast: String, val devanagari: String, val fixed: Boolean, val symbol: String, val nature: String, val use: String)
data class VaraInfo(val iast: String, val tamil: String, val lord: String, val devanagari: String, val english: String, val nature: String)
data class RasiInfo(val iast: String, val devanagari: String, val tamilMonth: String, val tamilMonthScript: String)
data class NatureInfo(val meaning: String, val uses: String)
data class Festival(val name: String, val tamilMonth: Int, val nakshatra: Int)
data class Graha(val key: String, val iast: String, val english: String, val science: String, val lore: String)
data class RingInfo(val key: String, val iast: String, val english: String, val color: Long)

object Tables {
    /** 0-based index = (tithi number 1..30) - 1 */
    val tithi = listOf(
        TithiInfo("Pratipadā", "Śukla", 1, "Nandā", "प्रतिपदा", "Beginnings, new projects, fine arts"),
        TithiInfo("Dvitīyā", "Śukla", 2, "Bhadrā", "द्वितीया", "Education, commerce, marriage, journeys"),
        TithiInfo("Tṛtīyā", "Śukla", 3, "Jayā", "तृतीया", "Legal actions, competitions, overcoming hurdles"),
        TithiInfo("Caturthī", "Śukla", 4, "Riktā", "चतुर्थी", "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo("Pañcamī", "Śukla", 5, "Pūrṇā", "पंचमी", "High-impact initiatives, rituals, real estate"),
        TithiInfo("Ṣaṣṭhī", "Śukla", 6, "Nandā", "षष्ठी", "Celebrations, beginnings, fine arts"),
        TithiInfo("Saptamī", "Śukla", 7, "Bhadrā", "सप्तमी", "Education, commerce, marriage, journeys"),
        TithiInfo("Aṣṭamī", "Śukla", 8, "Jayā", "अष्टमी", "Legal actions, competitions, overcoming hurdles"),
        TithiInfo("Navamī", "Śukla", 9, "Riktā", "नवमी", "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo("Daśamī", "Śukla", 10, "Pūrṇā", "दशमी", "High-impact initiatives, rituals, real estate"),
        TithiInfo("Ekādaśī", "Śukla", 11, "Nandā", "एकादशी", "Celebrations, beginnings, fine arts"),
        TithiInfo("Dvādaśī", "Śukla", 12, "Bhadrā", "द्वादशी", "Education, commerce, marriage, journeys"),
        TithiInfo("Trayodaśī", "Śukla", 13, "Jayā", "त्रयोदशी", "Legal actions, competitions, overcoming hurdles"),
        TithiInfo("Caturdaśī", "Śukla", 14, "Riktā", "चतुर्दशी", "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo("Pūrṇimā", "Śukla", 15, "Pūrṇā", "पूर्णिमा", "High-impact initiatives, rituals, real estate"),
        TithiInfo("Pratipadā", "Kṛṣṇa", 1, "Nandā", "प्रतिपदा", "Beginnings, new projects, fine arts"),
        TithiInfo("Dvitīyā", "Kṛṣṇa", 2, "Bhadrā", "द्वितीया", "Education, commerce, marriage, journeys"),
        TithiInfo("Tṛtīyā", "Kṛṣṇa", 3, "Jayā", "तृतीया", "Legal actions, competitions, overcoming hurdles"),
        TithiInfo("Caturthī", "Kṛṣṇa", 4, "Riktā", "चतुर्थी", "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo("Pañcamī", "Kṛṣṇa", 5, "Pūrṇā", "पंचमी", "High-impact initiatives, rituals, real estate"),
        TithiInfo("Ṣaṣṭhī", "Kṛṣṇa", 6, "Nandā", "षष्ठी", "Celebrations, beginnings, fine arts"),
        TithiInfo("Saptamī", "Kṛṣṇa", 7, "Bhadrā", "सप्तमी", "Education, commerce, marriage, journeys"),
        TithiInfo("Aṣṭamī", "Kṛṣṇa", 8, "Jayā", "अष्टमी", "Legal actions, competitions, overcoming hurdles"),
        TithiInfo("Navamī", "Kṛṣṇa", 9, "Riktā", "नवमी", "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo("Daśamī", "Kṛṣṇa", 10, "Pūrṇā", "दशमी", "High-impact initiatives, rituals, real estate"),
        TithiInfo("Ekādaśī", "Kṛṣṇa", 11, "Nandā", "एकादशी", "Celebrations, beginnings, fine arts"),
        TithiInfo("Dvādaśī", "Kṛṣṇa", 12, "Bhadrā", "द्वादशी", "Education, commerce, marriage, journeys"),
        TithiInfo("Trayodaśī", "Kṛṣṇa", 13, "Jayā", "त्रयोदशी", "Legal actions, competitions, overcoming hurdles"),
        TithiInfo("Caturdaśī", "Kṛṣṇa", 14, "Riktā", "चतुर्दशी", "Surgical ops, demolitions, purification, debt settlement"),
        TithiInfo("Amāvāsyā", "Kṛṣṇa", 15, "Pūrṇā", "अमावस्या", "High-impact initiatives, rituals, real estate")
    )
    val nakshatra = listOf(
        NakshatraInfo("Aśvinī", "अश्विनी", "அசுவினி", "ksipra", "Ashvins (Divine Twins)", "Swift, Healing"),
        NakshatraInfo("Bharaṇī", "भरणी", "பரணி", "ugra", "Yama (God of Death)", "Fierce, Restrictive"),
        NakshatraInfo("Kṛttikā", "कृत्तिका", "கார்த்திகை", "misra", "Agni (Fire God)", "Mixed, Sharp"),
        NakshatraInfo("Rohiṇī", "रोहिणी", "ரோகிணி", "dhruva", "Prajapati (Creator)", "Fixed, Fertile"),
        NakshatraInfo("Mṛgaśīrṣa", "मृगशीर्ष", "மிருகசீரிடம்", "mrdu", "Soma (Moon)", "Gentle, Inquisitive"),
        NakshatraInfo("Ārdrā", "आर्द्रा", "திருவாதிரை", "tiksna", "Rudra (Storm God)", "Sharp, Transformative"),
        NakshatraInfo("Punarvasu", "पुनर्वसु", "புனர்பூசம்", "cara", "Aditi (Mother of Gods)", "Movable, Renewing"),
        NakshatraInfo("Puṣya", "पुष्य", "பூசம்", "ksipra", "Brihaspati (Jupiter)", "Swift, Nourishing"),
        NakshatraInfo("Āśleṣā", "आश्लेषा", "ஆயில்யம்", "tiksna", "Sarpas (Serpents)", "Sharp, Piercing"),
        NakshatraInfo("Maghā", "मघा", "மகம்", "ugra", "Pitris (Ancestors)", "Fierce, Royal"),
        NakshatraInfo("Pūrva Phalgunī", "पूर्वफल्गुनी", "பூரம்", "ugra", "Bhaga (God of Prosperity)", "Fierce, Creative"),
        NakshatraInfo("Uttara Phalgunī", "उत्तरफल्गुनी", "உத்திரம்", "dhruva", "Aryaman (God of Patronage)", "Fixed, Enduring"),
        NakshatraInfo("Hasta", "हस्त", "அஸ்தம்", "ksipra", "Savitr (Sun God)", "Swift, Dexterous"),
        NakshatraInfo("Citrā", "चित्रा", "சித்திரை", "mrdu", "Tvashtar (Divine Architect)", "Gentle, Artistic"),
        NakshatraInfo("Svātī", "स्वाती", "சுவாதி", "cara", "Vayu (Wind God)", "Movable, Adaptable"),
        NakshatraInfo("Viśākhā", "विशाखा", "விசாகம்", "misra", "Indragni (Indra+Agni)", "Mixed, Purpose-Driven"),
        NakshatraInfo("Anurādhā", "अनुराधा", "அனுஷம்", "mrdu", "Mitra (Divine Friend)", "Gentle, Devotional"),
        NakshatraInfo("Jyeṣṭhā", "ज्येष्ठा", "கேட்டை", "tiksna", "Indra (King of Gods)", "Sharp, Protective"),
        NakshatraInfo("Mūla", "मूल", "மூலம்", "tiksna", "Nirriti (Goddess of Destruction)", "Sharp, Investigating"),
        NakshatraInfo("Pūrva Āṣāḍhā", "पूर्वाषाढा", "பூராடம்", "ugra", "Apas (Waters)", "Fierce, Invincible"),
        NakshatraInfo("Uttara Āṣāḍhā", "उत्तराषाढा", "உத்திராடம்", "dhruva", "Vishvedevas (All Gods)", "Fixed, Victorious"),
        NakshatraInfo("Śravaṇa", "श्रवण", "திருவோணம்", "cara", "Vishnu (Preserver)", "Movable, Receptive"),
        NakshatraInfo("Dhaniṣṭhā", "धनिष्ठा", "அவிட்டம்", "cara", "Ashta Vasus (Eight Deities)", "Movable, Rhythmic"),
        NakshatraInfo("Śatabhiṣaj", "शतभिषक्", "சதயம்", "cara", "Varuna (God of Waters)", "Movable, Curative"),
        NakshatraInfo("Pūrva Bhādrapadā", "पूर्वभाद्रपदा", "பூரட்டாதி", "ugra", "Aja Ekapada (One-footed Goat)", "Fierce, Ascetic"),
        NakshatraInfo("Uttara Bhādrapadā", "उत्तरभाद्रपदा", "உத்திரட்டாதி", "dhruva", "Ahirbudhnya (Serpent Dragon)", "Fixed, Grounded"),
        NakshatraInfo("Revatī", "रेवती", "ரேவதி", "mrdu", "Pushan (Nourisher)", "Gentle, Nurturing")
    )
    val yoga = listOf(
        YogaInfo("Viṣkambha", "विष्कम्भ", false, "Obstruction, initial friction"),
        YogaInfo("Prīti", "प्रीति", true, "Love, affection, satisfaction"),
        YogaInfo("Āyuṣmān", "आयुष्मान", true, "Long life, vitality, good health"),
        YogaInfo("Saubhāgya", "सौभाग्य", true, "Good fortune, prosperity, auspiciousness"),
        YogaInfo("Śobhana", "शोभन", true, "Beautiful, splendid, virtuous"),
        YogaInfo("Atigaṇḍa", "अतिगण्ड", false, "Severe complications, high turbulence"),
        YogaInfo("Sukarmā", "सुकर्मा", true, "Good actions, virtuous deeds, merit"),
        YogaInfo("Dhṛti", "धृति", true, "Steadfastness, patience, determination"),
        YogaInfo("Śūla", "शूल", false, "Sharp conflict, pain, weapons, surgery"),
        YogaInfo("Gaṇḍa", "गण्ड", false, "Emotional knots, tangles, administrative blocks"),
        YogaInfo("Vṛddhi", "वृद्धि", true, "Growth, increase, prosperity, expansion"),
        YogaInfo("Dhruva", "ध्रुव", true, "Fixed, stable, permanent, unchanging"),
        YogaInfo("Vyāghāta", "व्याघात", false, "Threatening, destructive, prone to sudden injury"),
        YogaInfo("Harṣaṇa", "हर्षण", true, "Joy, delight, happiness, celebration"),
        YogaInfo("Vajra", "वज्र", false, "Volatile, piercing, sharp like thunderbolt"),
        YogaInfo("Siddhi", "सिद्धि", true, "Accomplishment, perfection, attainment"),
        YogaInfo("Vyatīpāta", "व्यतिपात", false, "Major directional calamity; avoid material initiatives"),
        YogaInfo("Varīyān", "वरियान्", true, "Excellent, best, superior quality"),
        YogaInfo("Parigha", "परिघ", false, "Gates/barriers, delays, opposition, obstacles"),
        YogaInfo("Śiva", "शिव", true, "Auspicious, benevolent, benevolent destruction"),
        YogaInfo("Siddha", "सिद्ध", true, "Perfected, accomplished, established"),
        YogaInfo("Sādhya", "साध्य", true, "Attainable, possible, achievable"),
        YogaInfo("Śubha", "शुभ", true, "Auspicious, favorable, beneficial"),
        YogaInfo("Śukla", "शुक्ल", true, "Bright, pure, clear, white"),
        YogaInfo("Brahma", "ब्रह्म", true, "Creative, expansive, universal consciousness"),
        YogaInfo("Aindra", "इन्द्र", true, "Power, leadership, sovereignty, strength"),
        YogaInfo("Vaidhṛti", "वैधृति", false, "Chaotic dissipation; unstable for worldly investments")
    )
    /** The 11 distinct karanas; use [karanaOfSlot] for the 60 slots. */
    val karanaKinds = listOf(
        KaranaInfo("Kiṃstughna", "किंस्तुघ्न", true, "Wild Beast", "Rebirth, Foundational", "Sowing seeds, charity, foundation stones"),
        KaranaInfo("Bava", "बव", false, "Lion", "Commanding, Courageous", "Leadership, fitness, health, initiation"),
        KaranaInfo("Bālava", "बालव", false, "Tiger / Leopard", "Intellectual, Active", "Study, spiritual rituals, sacred tasks"),
        KaranaInfo("Kaulava", "कौलव", false, "Boar / Pig", "Cooperative, Grounded", "Social alliances, contracts, partnerships"),
        KaranaInfo("Taitila", "तैतिल", false, "Rhinoceros", "Defensive, Resilient", "Construction, official paperwork, boundaries"),
        KaranaInfo("Gara", "गर", false, "Elephant", "Diligent, Heavy", "Agriculture, groundwork, physical labor"),
        KaranaInfo("Vaṇij", "वणिज", false, "Merchant", "Commercial, Agile", "Trade, financial exchanges, sales trips"),
        KaranaInfo("Viṣṭi", "विष्टि", false, "Donkey", "Volatile, Destructive", "avoid all auspicious events"),
        KaranaInfo("Śakuni", "शकुनि", true, "Raven / Bird", "Diagnostic, Remedial", "Medicine, therapy, settling long disputes"),
        KaranaInfo("Catuṣpāda", "चतुष्पाद", true, "Bull / Quadruped", "Grounded, Material", "Ancestral rites (Shraddha), animal care, soil"),
        KaranaInfo("Nāga", "नाग", true, "Serpent", "Covert, Penetrating", "Mining, excavations, secret negotiations")
    )
    /** slot 0..59 (0-based, = k - 1) -> index into [karanaKinds] */
    val karanaSlot = intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    fun karanaOfSlot(slot: Int): KaranaInfo = karanaKinds[karanaSlot[slot]]
    val vara = listOf(
        VaraInfo("Ravivāra", "ஞாயிறு", "Sūrya", "रविवार", "Sunday", "Vitality, leadership, authority"),
        VaraInfo("Somavāra", "திங்கள்", "Candra", "सोमवार", "Monday", "Mind, emotions, nurturing"),
        VaraInfo("Maṅgalavāra", "செவ்வாய்", "Maṅgala", "मङ्गलवार", "Tuesday", "Energy, courage, conflict"),
        VaraInfo("Budhavāra", "புதன்", "Budha", "बुधवार", "Wednesday", "Intellect, communication, trade"),
        VaraInfo("Guruvāra", "வியாழன்", "Guru", "गुरुवार", "Thursday", "Wisdom, expansion, prosperity"),
        VaraInfo("Śukravāra", "வெள்ளி", "Śukra", "शुक्रवार", "Friday", "Love, beauty, creativity, luxury"),
        VaraInfo("Śanivāra", "சனி", "Śani", "शनिवार", "Saturday", "Discipline, karma, longevity, obstacles")
    )
    val rasi = listOf(
        RasiInfo("Meṣa", "मेष", "Chithirai", "சித்திரை"),
        RasiInfo("Vṛṣabha", "वृषभ", "Vaikāsi", "வைகாசி"),
        RasiInfo("Mithuna", "मिथुन", "Āni", "ஆனி"),
        RasiInfo("Karkaṭa", "कर्कट", "Āḍi", "ஆடி"),
        RasiInfo("Siṃha", "सिंह", "Āvaṇi", "ஆவணி"),
        RasiInfo("Kanyā", "कन्या", "Puraṭṭāsi", "புரட்டாசி"),
        RasiInfo("Tulā", "तुला", "Aippasi", "ஐப்பசி"),
        RasiInfo("Vṛścika", "वृश्चिक", "Kārttikai", "கார்த்திகை"),
        RasiInfo("Dhanus", "धनुस्", "Mārgazhi", "மார்கழி"),
        RasiInfo("Makara", "मकर", "Thai", "தை"),
        RasiInfo("Kumbha", "कुम्भ", "Māsi", "மாசி"),
        RasiInfo("Mīna", "मीन", "Panguni", "பங்குனி")
    )
    val samvatsara = listOf("Prabhava", "Vibhava", "Śukla", "Pramoda", "Prajāpati", "Āṅgīrasa", "Śrīmukha", "Bhāva", "Yuvan", "Dhātṛ", "Īśvara", "Bahudhānya", "Pramāthin", "Vikrama", "Vṛṣa", "Citrabhānu", "Svabhānu", "Tāraṇa", "Pārthiva", "Vyaya", "Sarvajit", "Sarvadhārin", "Virodhin", "Vikṛti", "Khara", "Nandana", "Vijaya", "Jaya", "Manmatha", "Durmukha", "Hemalamba", "Vilamba", "Vikārin", "Śārvari", "Plava", "Śubhakṛt", "Śobhakṛt", "Krodhin", "Viśvāvasu", "Parābhava", "Plavaṅga", "Kīlaka", "Saumya", "Sādhāraṇa", "Virodhikṛt", "Paridhāvin", "Pramādin", "Ānanda", "Rākṣasa", "Nala", "Piṅgala", "Kālayukta", "Siddhārthin", "Raudra", "Durmati", "Dundubhi", "Rudhirodgārin", "Raktākṣin", "Krodhana", "Akṣaya")
    val horaChaldean = listOf("Śani", "Guru", "Maṅgala", "Sūrya", "Śukra", "Budha", "Candra")
    /** index 0 = Sunday; value = which eighth of daylight (1-based) */
    val rahuKalam = intArrayOf(8, 2, 7, 5, 6, 4, 3)
    val yamagandam = intArrayOf(5, 4, 3, 2, 1, 7, 6)
    val kulikai = intArrayOf(7, 6, 5, 4, 3, 2, 1)
    val natures = mapOf(
        "dhruva" to NatureInfo("fixed", "foundations, house-warming (gṛhapraveśa), planting"),
        "cara" to NatureInfo("movable", "travel, vehicles"),
        "ksipra" to NatureInfo("swift", "learning, medicine, trade"),
        "mrdu" to NatureInfo("soft", "arts, friendship, new clothes"),
        "ugra" to NatureInfo("fierce", "avoided for gentle work"),
        "tiksna" to NatureInfo("sharp", "avoided for gentle work"),
        "misra" to NatureInfo("mixed", "routine work")
    )
    val festivals = listOf(
        Festival("Kārttikai Dīpam", 7, 2),
        Festival("Thai Pūsam", 9, 7),
        Festival("Paṅguni Uttiram", 11, 11),
        Festival("Vaikāsi Visākam", 1, 15)
    )
    val weddingNakshatras = setOf(3, 4, 9, 11, 12, 14, 16, 18, 20, 25, 26)
    val weddingAvoidMonths = setOf(3, 5, 8)
    val ashubhaYogas = setOf(1, 6, 9, 10, 13, 15, 17, 19, 27)
    const val DISCLAIMER = "Teaching-level rules used in the film. Real muhūrta selection also weighs lagna, tārābalam, candrabalam, month and personal charts; present results as guidance."
    /** data/glossary.json — every UI term has a plain-language one-liner */
    val glossary = linkedMapOf(
        "Pañcāṅga" to "\"Five limbs\" — the almanac of vāra, tithi, nakṣatra, yoga and karaṇa, all read from the Sun and Moon.",
        "Vāra" to "The weekday. In the Tamil convention it changes at sunrise, not midnight, and is named for the planet ruling its first horā.",
        "Tithi" to "A lunar day: each 12° the Moon gains on the Sun. Thirty tithis make one synodic month.",
        "Pakṣa" to "A fortnight. Śukla (bright, waxing) runs to Pūrṇimā; Kṛṣṇa (dark, waning) runs to Amāvāsyā.",
        "Śukla" to "The bright, waxing fortnight — tithis 1 to 15, ending at the full moon.",
        "Kṛṣṇa" to "The dark, waning fortnight — tithis 16 to 30, ending at the new moon.",
        "Pūrṇimā" to "Full moon: the 15th tithi, when the Moon is 168°–180° from the Sun.",
        "Amāvāsyā" to "New moon: the 30th tithi, when the Moon closes the last 12° on the Sun.",
        "Nakṣatra" to "A lunar mansion: one of 27 equal stretches of 13°20′ along the ecliptic. The Moon crosses one in about a day.",
        "Pada" to "A quarter of a nakṣatra (3°20′). 27 × 4 = 108 padas circle the sky.",
        "Yoga" to "The sum of the Sun's and Moon's longitudes, divided into 27 parts of 13°20′. Nine of the 27 are considered aśubha.",
        "Karaṇa" to "Half a tithi (6° of elongation). 60 slots per month: seven movable names cycle eight times, plus four fixed ones.",
        "Viṣṭi" to "Also called Bhadrā — the one movable karaṇa that is avoided for auspicious beginnings.",
        "Śubha" to "Auspicious, favourable.",
        "Aśubha" to "Inauspicious — traditionally avoided for new undertakings.",
        "Nāḻigai" to "The Tamil ghaṭikā: 1/60 of a day, 24 minutes. The day is counted in nāḻigai from sunrise.",
        "Vināḻigai" to "1/60 of a nāḻigai — 24 seconds.",
        "Muhūrta" to "Two nāḻigai (48 minutes); also an auspicious window chosen for an event. Always guidance, never a guarantee.",
        "Abhijit" to "The 8th of the 15 daytime muhūrtas, around local noon — widely held auspicious.",
        "Rāhu kālam" to "One eighth of daylight, chosen by weekday, traditionally avoided for beginnings.",
        "Yamagaṇḍam" to "Another eighth of daylight by weekday, avoided for beginnings.",
        "Kuḷikai" to "The eighth of daylight ruled by Gulika (Śani's son); work begun in it is said to repeat.",
        "Horā" to "One of 24 planetary hours per day, lords in Chaldean order: Śani, Guru, Maṅgala, Sūrya, Śukra, Budha, Candra.",
        "Rāśi" to "One of the 12 sidereal signs of 30°. The Sun's rāśi names the Tamil solar month.",
        "Ayanāṁśa" to "The offset between the tropical and sidereal zodiacs (Lahiri: about 24°14′ in 2026), from the precession of the equinoxes.",
        "Nirayana" to "Sidereal — longitudes measured from the fixed stars (Spica at 180°), not the moving equinox.",
        "Elongation" to "E = λ☾ − λ☉: how far the Moon is ahead of the Sun. It sets both the tithi and the Moon's phase.",
        "Ecliptic" to "The Sun's yearly path across the stars. The Moon is never more than about 5° from it.",
        "Saṃvatsara" to "The year name in the 60-year Jovian cycle. The Tamil year begins in Chithirai.",
        "Saṅkrānti" to "The moment the Sun enters a new rāśi — the start of a Tamil solar month.",
        "Kṣaya" to "A tithi that begins and ends between two sunrises, so no day is named for it.",
        "Adhika" to "A tithi that is in force at two successive sunrises, so two days share its name.",
        "Candrāṣṭamam" to "Days when the Moon is in the 8th rāśi from one's birth rāśi; avoided for important work.",
        "Graha" to "A 'seizer' — the visible planets, Sun and Moon, plus the lunar nodes Rāhu and Ketu."
    )
    /** data/sky.json */
    val grahas = listOf(
        Graha("sun", "Sūrya", "Sun", "A G2 star 1 AU away; its path against the stars is the ecliptic.", "Soul and sovereignty; lord of Ravivāra and of Siṃha."),
        Graha("moon", "Candra", "Moon", "Earth's satellite, 384,400 km away; laps the zodiac in 27.3 days.", "Mind and emotion; lord of Somavāra and of Karkaṭa."),
        Graha("mercury", "Budha", "Mercury", "Innermost planet; never strays more than 28° from the Sun.", "Intellect and speech; lord of Budhavāra, Mithuna and Kanyā."),
        Graha("venus", "Śukra", "Venus", "Brightest planet, wrapped in sulphuric cloud; within 47° of the Sun.", "Beauty, art and pleasure; lord of Śukravāra, Vṛṣabha and Tulā."),
        Graha("mars", "Maṅgala", "Mars", "The red planet; its retrograde loops puzzled every early astronomer.", "Courage and conflict; lord of Maṅgalavāra, Meṣa and Vṛścika."),
        Graha("jupiter", "Guru", "Jupiter", "The giant; spends about a year in each rāśi, which names the 60-year cycle.", "Wisdom and the teacher of the gods; lord of Guruvāra, Dhanus and Mīna."),
        Graha("saturn", "Śani", "Saturn", "Ringed and slow: 29.5 years round the zodiac, about 2½ years per rāśi.", "Time, discipline and karma; lord of Śanivāra, Makara and Kumbha."),
        Graha("rahu", "Rāhu", "North lunar node", "Where the Moon's orbit crosses the ecliptic going north; eclipses happen near the nodes.", "The shadow graha said to swallow the Sun and Moon at eclipses."),
        Graha("ketu", "Ketu", "South lunar node", "Always opposite Rāhu; the nodes drift backwards once round in 18.6 years.", "The headless body of the demon; detachment and liberation."),
        Graha("earth", "Pṛthvī", "Earth", "The observer's home: every limb is measured from here.", "Bhūmi Devī, the goddess who bears all.")
    )
    val rings = listOf(
        RingInfo("nazhigai", "Nāḻigai", "Hour dial — 60 per day from sunrise", 0xFFE3AE4A),
        RingInfo("nakshatra", "Nakṣatra", "Lunar mansions — Moon among the stars", 0xFF5B8DEF),
        RingInfo("tithi", "Tithi", "Lunar day — Moon's lead on the Sun", 0xFFCBD5DE),
        RingInfo("yoga", "Yoga", "Union — Sun + Moon", 0xFF63B8B2),
        RingInfo("karana", "Karaṇa", "Half lunar day", 0xFFC07A43),
        RingInfo("vara", "Vāra", "Weekday", 0xFFF3D491),
        RingInfo("rasi", "Rāśi", "Zodiac sign", 0xFFE3AE4A)
    )
    fun graha(key: String) = grahas.first { it.key == key }
    fun ring(key: String) = rings.first { it.key == key }
}
